default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  username: postgres
  password: gfhjkm123
  host: localhost
  timeout: 5000
  port: 5432


development:
  <<: *default
  database: depot_dev

test:
  <<: *default
  database: depot_test